# Generated by Django 2.2 on 2019-04-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration_test_app', '0002_historicalmodelwithcustomattrforeignkey_modelwithcustomattrforeignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmodelwithcustomattrforeignkey',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalyar',
            name='history_user',
        ),
    ]
